pub(crate) const REQUIRED_ACTUAL_MANIFEST_EVIDENCE: &[&str] = &[
    "katana-language-editor = { path = \"../../../katana-language-editor/crates/katana-language-editor\" }",
    "katana-language-editor-egui = { path = \"../../../katana-language-editor/crates/katana-language-editor-egui\" }",
];
pub(crate) const REQUIRED_ACTUAL_WRAPPER_EVIDENCE: &[&str] = &[
    "#[path = \"integration/editor/kle_downstream_adapter.rs\"]",
    "mod editor_kle_downstream_adapter;",
    "mod editor_layout_persistence;",
    "mod editor_navigation;",
    "mod editor_toggle_view_modes;",
    "mod editor_view_modes;",
];
pub(crate) const REQUIRED_ACTUAL_ADAPTER_EVIDENCE: &[&str] = &[
    "kle_event_action_stream_updates_real_katana_editor_state",
    "KatanaKleEditorAdapter::drain_editor",
    "EguiLanguageEditor::new(editor_config())",
    "EditorAction::SaveDocument",
    "active_document_buffer(&harness)",
    "KatanA document should become dirty after KLE content event",
    "kle_format_document_records_scoped_undo_state",
    "editor_text_edit_id",
    "TextEdit::load_state",
    "kle_content_event_refreshes_dirty_preview_search_and_diagnostics",
    "preview_hash_for_test",
    "doc_search_matches.len()",
    "last_buffer_update",
    "EditorScrollSource::Preview",
    ".with_target_line(7)",
    "ScrollSource::Neither",
    "last_scroll_to_line",
    "std::fs::read_to_string(&second_path)",
    "kle_authoring_adapter_executes_authoring_commands_on_fresh_documents",
    "assert_authoring_command_effect",
    "kle_authoring_action_records_real_katana_cursor_restore",
    "pending_editor_cursor_for_test",
    "set_editor_cursor_range_for_test",
    "author.insert_table",
    "CodeBlockKind::all()",
    "kle_image_ingest_action_executes_real_katana_asset_ingest",
    "set_katana_image_ingest_fixture_for_test",
    "take_katana_image_ingest_fixture_for_test",
    "execute_katana_image_ingest_for_test",
    "EditorAction::IngestImageFile",
    "EditorAction::IngestClipboardImage",
    "EditorAction::IngestClipboardFileUrls",
    "let clipboard_urls = vec![",
    "file:///tmp/katanA-test-ingest-a.png",
    "katanA-fixture-webp-from-clipboard-file-urls",
    "assert_real_katana_image_ingest(&mut harness, &first_path, \"webp\", &tertiary_payload, 3)",
    "asset/img",
    "RefreshExplorer",
    "EditorAction::ApplyDiagnosticFix",
    "EditorAction::ApplyAllDiagnosticFixes",
    "EditorAction::ApplyProblemsFixes",
    "AppAction::ApplyLintFixes",
    "kle_to_katana_diagnostic_fix",
    "diff_review_snapshot()",
    "ConfirmCurrentDiffReviewFile",
    "kle_diagnostic_fix_action_opens_real_katana_lint_fix_review",
    "kle_diagnostic_fix_all_action_opens_real_katana_lint_fix_review",
    "kle_problems_fix_actions_open_real_katana_lint_fix_review",
    "kle_kuc_text_area_ime_commit_star_reaches_real_katana_buffer",
    "TextAreaAction::composition(",
    "TextAreaAction::ime_commit(star_commit_text)",
    "TextAreaEvent::ImeComposition(",
    "TextAreaCompositionPhase::Update",
    "TextAreaEvent::ImeCommit(star_commit_text.to_string())",
    "TextAreaEvent::EmojiInput { grapheme_count: 1 }",
    "TextAreaEvent::Change(star_commit_text.to_string())",
    ".set_text(composition_text.to_string())",
    "fn ime_commit_text(events: &[TextAreaEvent]) -> Option<&str>",
    "let star_commit_text = \"⭐️\";",
    "let commit_text =",
    "ime_commit_text(&commit.events)",
    "TextOffset::new(composition_text.chars().count())",
    "assert_eq!(commit_text, star_commit_text);",
    "insert_at(",
    "KatanaKleEditorAdapter::drain_editor",
    "assert_eq!(active_document_buffer(&harness), \"かな⭐️\")",
    "IME commit text written through KLE API should mark the document dirty",
    "kle_document_search_markdown_aware_matches_and_refreshes_via_kle_adapter",
];
pub(crate) const REQUIRED_ACTUAL_BASELINE_TESTS: &[&str] = &[
    "test_integration_editor_line_numbers_visibility",
    "input_assist_code_block_button_updates_editor_buffer",
    "code_block_kind_menu_closes_when_editor_is_clicked",
    "editor_context_menu_authoring_heading1_updates_editor_state_via_real_ui_routing",
    "editor_context_menu_save_button_persists_editor_buffer_state",
    "editor_context_menu_format_button_updates_formatted_markdown_buffer",
    "editor_select_and_jump_real_editor_frame_updates_last_scroll_and_accesskit_tree",
    "editor_scroll_sync_reacts_as_editor_coordinator_when_host_sets_preview_source",
];
pub(crate) const REQUIRED_ACTUAL_TOOLBAR_POPUP_TESTS: &[&str] = &[
    "popup_position_anchors_below_cursor",
    "popup_position_stays_inside_viewport_edges",
    "popup_stays_available_after_editor_focus_moves_to_toolbar",
    "popup_stays_available_when_child_menu_is_open",
];
pub(crate) const FORBIDDEN_PATCH_EVIDENCE: &[&str] = &[
    "force_view_mode",
    "# Updated from KLE adapter",
    "katana_language_editor::LanguageEditor::poll_events",
    "Arc<dyn SyntaxHighlighter>",
];
