use super::context_menu_contract_entry_types::LeafSpec;

const CODE: &str = "crates/katana-ui/src/markdown_authoring_op.rs";

pub(super) const CODE_SPECS: &[LeafSpec] = &[
    LeafSpec {
        id: "context.structure.code.text",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 5,
        marker: "Text,",
    },
    LeafSpec {
        id: "context.structure.code.markdown",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 6,
        marker: "Markdown,",
    },
    LeafSpec {
        id: "context.structure.code.bash",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 7,
        marker: "Bash,",
    },
    LeafSpec {
        id: "context.structure.code.zsh",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 8,
        marker: "Zsh,",
    },
    LeafSpec {
        id: "context.structure.code.mermaid",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 9,
        marker: "Mermaid,",
    },
    LeafSpec {
        id: "context.structure.code.drawio",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 10,
        marker: "Drawio,",
    },
    LeafSpec {
        id: "context.structure.code.plantuml",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 11,
        marker: "Plantuml,",
    },
    LeafSpec {
        id: "context.structure.code.json",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 12,
        marker: "Json,",
    },
    LeafSpec {
        id: "context.structure.code.yaml",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 13,
        marker: "Yaml,",
    },
    LeafSpec {
        id: "context.structure.code.toml",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 14,
        marker: "Toml,",
    },
    LeafSpec {
        id: "context.structure.code.rust",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 15,
        marker: "Rust,",
    },
    LeafSpec {
        id: "context.structure.code.typescript",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 16,
        marker: "Typescript,",
    },
    LeafSpec {
        id: "context.structure.code.javascript",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 17,
        marker: "Javascript,",
    },
    LeafSpec {
        id: "context.structure.code.python",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 18,
        marker: "Python,",
    },
    LeafSpec {
        id: "context.structure.code.html",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 19,
        marker: "Html,",
    },
    LeafSpec {
        id: "context.structure.code.css",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 20,
        marker: "Css,",
    },
    LeafSpec {
        id: "context.structure.code.sql",
        parent_path: "root/Edit/Code",
        root_slot: None,
        path: CODE,
        line: 21,
        marker: "Sql,",
    },
];
