use super::context_menu_contract_entry_types::LeafSpec;

const MENU: &str = "crates/katana-ui/src/views/panels/editor/context_menu.rs";

pub(super) const ROOT_AND_EDIT_SPECS: &[LeafSpec] = &[
    LeafSpec {
        id: "context.structure.root.save",
        parent_path: "root",
        root_slot: Some(0),
        path: MENU,
        line: 19,
        marker: "i18n.action.save",
    },
    LeafSpec {
        id: "context.structure.root.format",
        parent_path: "root",
        root_slot: Some(1),
        path: MENU,
        line: 23,
        marker: "should_offer_markdown_format",
    },
    LeafSpec {
        id: "context.structure.root.edit",
        parent_path: "root",
        root_slot: Some(2),
        path: MENU,
        line: 32,
        marker: "i18n.settings.shortcuts.edit",
    },
    LeafSpec {
        id: "context.structure.root.ingest",
        parent_path: "root",
        root_slot: Some(3),
        path: MENU,
        line: 39,
        marker: "MenuButtonOps::show",
    },
    LeafSpec {
        id: "context.structure.format.editable-markdown-only",
        parent_path: "root/Format",
        root_slot: None,
        path: MENU,
        line: 190,
        marker: "extension.eq_ignore_ascii_case(\"md\")",
    },
    LeafSpec {
        id: "context.structure.edit.parent-path",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 32,
        marker: "MenuButtonOps::show",
    },
    LeafSpec {
        id: "context.structure.ingest.parent-path",
        parent_path: "root/Ingest",
        root_slot: None,
        path: MENU,
        line: 39,
        marker: "MenuButtonOps::show",
    },
    LeafSpec {
        id: "context.structure.edit.bold",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 62,
        marker: "MarkdownAuthoringOp::Bold",
    },
    LeafSpec {
        id: "context.structure.edit.italic",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 69,
        marker: "MarkdownAuthoringOp::Italic",
    },
    LeafSpec {
        id: "context.structure.edit.strikethrough",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 76,
        marker: "MarkdownAuthoringOp::Strikethrough",
    },
    LeafSpec {
        id: "context.structure.edit.inline-code",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 83,
        marker: "MarkdownAuthoringOp::InlineCode",
    },
    LeafSpec {
        id: "context.structure.edit.heading-1",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 100,
        marker: "MarkdownAuthoringOp::Heading1",
    },
    LeafSpec {
        id: "context.structure.edit.heading-2",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 107,
        marker: "MarkdownAuthoringOp::Heading2",
    },
    LeafSpec {
        id: "context.structure.edit.heading-3",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 114,
        marker: "MarkdownAuthoringOp::Heading3",
    },
    LeafSpec {
        id: "context.structure.edit.bullet-list",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 125,
        marker: "MarkdownAuthoringOp::BulletList",
    },
    LeafSpec {
        id: "context.structure.edit.numbered-list",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 132,
        marker: "MarkdownAuthoringOp::NumberedList",
    },
    LeafSpec {
        id: "context.structure.edit.blockquote",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 139,
        marker: "MarkdownAuthoringOp::Blockquote",
    },
    LeafSpec {
        id: "context.structure.edit.horizontal-rule",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 149,
        marker: "MarkdownAuthoringOp::HorizontalRule",
    },
    LeafSpec {
        id: "context.structure.edit.insert-link",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 160,
        marker: "MarkdownAuthoringOp::InsertLink",
    },
    LeafSpec {
        id: "context.structure.edit.insert-table",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 167,
        marker: "MarkdownAuthoringOp::InsertTable",
    },
    LeafSpec {
        id: "context.structure.edit.code-submenu",
        parent_path: "root/Edit",
        root_slot: None,
        path: MENU,
        line: 143,
        marker: "CodeBlockMenuOps::show",
    },
];
