use super::{
    leaf_inventory_host_e2e::{
        EXTERNAL_INGEST_HOST_E2E, FORMAT_HOST_E2E, MISSING_HOST_E2E, SAVE_HOST_E2E,
    },
    leaf_inventory_types::{
        LEAF_COMMAND_CHROME_HARNESS, LeafCapability, LeafDeclaration, leaf, leaf_with_harness,
        leaf_with_harness_host, leaf_with_host,
    },
};

pub(crate) const REQUIRED_LEAF_COUNT: usize = 48;

pub(super) const TOOLBAR: &str = "authoring-toolbar";
pub(super) const CONTEXT: &str = "context-menu-actions";
const CODE: &str = "code-block-menu";
const IMAGE: &str = "image-ingest";
const TOOLBAR_SOURCE: &str = "crates/katana-ui/src/views/panels/editor/toolbar.rs";
const CONTEXT_SOURCE: &str = "crates/katana-ui/src/views/panels/editor/context_menu.rs";
const CODE_SOURCE: &str = "crates/katana-ui/src/markdown_authoring_op.rs";
const IMAGE_SOURCE: &str = "crates/katana-ui/src/views/panels/editor/context_menu_image_ingest.rs";

#[rustfmt::skip]
pub(crate) const LEAVES: &[LeafCapability] = &[
    leaf_with_harness(
        TOOLBAR,
        "toolbar.bold",
        TOOLBAR_SOURCE,
        59,
        "MarkdownAuthoringOp::Bold",
        "public_show_toolbar_routes_all_actions_and_lifecycle",
        LEAF_COMMAND_CHROME_HARNESS,
    ),
    leaf_with_harness(
        TOOLBAR,
        "toolbar.italic",
        TOOLBAR_SOURCE,
        66,
        "MarkdownAuthoringOp::Italic",
        "public_show_toolbar_routes_all_actions_and_lifecycle",
        LEAF_COMMAND_CHROME_HARNESS,
    ),
    leaf_with_harness(
        TOOLBAR,
        "toolbar.strikethrough",
        TOOLBAR_SOURCE,
        73,
        "MarkdownAuthoringOp::Strikethrough",
        "public_show_toolbar_routes_all_actions_and_lifecycle",
        LEAF_COMMAND_CHROME_HARNESS,
    ),
    leaf_with_harness(
        TOOLBAR,
        "toolbar.inline-code",
        TOOLBAR_SOURCE,
        80,
        "MarkdownAuthoringOp::InlineCode",
        "public_show_toolbar_routes_all_actions_and_lifecycle",
        LEAF_COMMAND_CHROME_HARNESS,
    ),
    leaf_with_harness(
        TOOLBAR,
        "toolbar.heading-1",
        TOOLBAR_SOURCE,
        90,
        "MarkdownAuthoringOp::Heading1",
        "public_show_toolbar_routes_all_actions_and_lifecycle",
        LEAF_COMMAND_CHROME_HARNESS,
    ),
    leaf_with_harness(
        TOOLBAR,
        "toolbar.heading-2",
        TOOLBAR_SOURCE,
        98,
        "MarkdownAuthoringOp::Heading2",
        "public_show_toolbar_routes_all_actions_and_lifecycle",
        LEAF_COMMAND_CHROME_HARNESS,
    ),
    leaf_with_harness(
        TOOLBAR,
        "toolbar.heading-3",
        TOOLBAR_SOURCE,
        106,
        "MarkdownAuthoringOp::Heading3",
        "public_show_toolbar_routes_all_actions_and_lifecycle",
        LEAF_COMMAND_CHROME_HARNESS,
    ),
    leaf_with_harness(
        TOOLBAR,
        "toolbar.bullet-list",
        TOOLBAR_SOURCE,
        116,
        "MarkdownAuthoringOp::BulletList",
        "public_show_toolbar_routes_all_actions_and_lifecycle",
        LEAF_COMMAND_CHROME_HARNESS,
    ),
    leaf_with_harness(
        TOOLBAR,
        "toolbar.numbered-list",
        TOOLBAR_SOURCE,
        124,
        "MarkdownAuthoringOp::NumberedList",
        "public_show_toolbar_routes_all_actions_and_lifecycle",
        LEAF_COMMAND_CHROME_HARNESS,
    ),
    leaf_with_harness(
        TOOLBAR,
        "toolbar.blockquote",
        TOOLBAR_SOURCE,
        132,
        "MarkdownAuthoringOp::Blockquote",
        "public_show_toolbar_routes_all_actions_and_lifecycle",
        LEAF_COMMAND_CHROME_HARNESS,
    ),
    leaf_with_harness(
        TOOLBAR,
        "toolbar.code-dropdown",
        TOOLBAR_SOURCE,
        137,
        "CodeBlockMenuPopupOps::show",
        "public_show_toolbar_routes_all_actions_and_lifecycle",
        LEAF_COMMAND_CHROME_HARNESS,
    ),
    leaf_with_harness_host(
        LeafDeclaration {
            parent_group: TOOLBAR,
            id: "toolbar.image-file",
            path: TOOLBAR_SOURCE,
            line: 146,
            marker: "AppAction::IngestImageFile",
            selector: "public_show_toolbar_routes_all_actions_and_lifecycle",
        },
        LEAF_COMMAND_CHROME_HARNESS,
        EXTERNAL_INGEST_HOST_E2E,
    ),
    leaf_with_host(CONTEXT, "context.save", CONTEXT_SOURCE, 19, "i18n.action.save", "public_show_context_menu_routes_save_format_authoring_and_ingest", SAVE_HOST_E2E),
    leaf_with_host(CONTEXT, "context.format-editable-markdown", CONTEXT_SOURCE, 23, "should_offer_markdown_format", "public_show_context_menu_routes_save_format_authoring_and_ingest", FORMAT_HOST_E2E),
    leaf(CONTEXT, "context.bold", CONTEXT_SOURCE, 62, "MarkdownAuthoringOp::Bold", "public_show_context_menu_routes_save_format_authoring_and_ingest"),
    leaf(CONTEXT, "context.italic", CONTEXT_SOURCE, 69, "MarkdownAuthoringOp::Italic", "public_show_context_menu_routes_save_format_authoring_and_ingest"),
    leaf(CONTEXT, "context.strikethrough", CONTEXT_SOURCE, 76, "MarkdownAuthoringOp::Strikethrough", "public_show_context_menu_routes_save_format_authoring_and_ingest"),
    leaf(CONTEXT, "context.inline-code", CONTEXT_SOURCE, 83, "MarkdownAuthoringOp::InlineCode", "public_show_context_menu_routes_save_format_authoring_and_ingest"),
    leaf(CONTEXT, "context.heading-1", CONTEXT_SOURCE, 100, "MarkdownAuthoringOp::Heading1", "public_show_context_menu_routes_save_format_authoring_and_ingest"),
    leaf(CONTEXT, "context.heading-2", CONTEXT_SOURCE, 107, "MarkdownAuthoringOp::Heading2", "public_show_context_menu_routes_save_format_authoring_and_ingest"),
    leaf(CONTEXT, "context.heading-3", CONTEXT_SOURCE, 114, "MarkdownAuthoringOp::Heading3", "public_show_context_menu_routes_save_format_authoring_and_ingest"),
    leaf(CONTEXT, "context.bullet-list", CONTEXT_SOURCE, 125, "MarkdownAuthoringOp::BulletList", "public_show_context_menu_routes_save_format_authoring_and_ingest"),
    leaf(CONTEXT, "context.numbered-list", CONTEXT_SOURCE, 132, "MarkdownAuthoringOp::NumberedList", "public_show_context_menu_routes_save_format_authoring_and_ingest"),
    leaf(CONTEXT, "context.blockquote", CONTEXT_SOURCE, 139, "MarkdownAuthoringOp::Blockquote", "public_show_context_menu_routes_save_format_authoring_and_ingest"),
    leaf(CONTEXT, "context.code-submenu", CONTEXT_SOURCE, 143, "CodeBlockMenuOps::show", "public_show_context_menu_routes_save_format_authoring_and_ingest"),
    leaf(CONTEXT, "context.horizontal-rule", CONTEXT_SOURCE, 149, "MarkdownAuthoringOp::HorizontalRule", "public_show_context_menu_routes_save_format_authoring_and_ingest"),
    leaf(CONTEXT, "context.insert-link", CONTEXT_SOURCE, 160, "MarkdownAuthoringOp::InsertLink", "public_show_context_menu_routes_save_format_authoring_and_ingest"),
    leaf(CONTEXT, "context.insert-table", CONTEXT_SOURCE, 167, "MarkdownAuthoringOp::InsertTable", "public_show_context_menu_routes_save_format_authoring_and_ingest"),
    leaf(CODE, "code.text", CODE_SOURCE, 5, "Text,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.markdown", CODE_SOURCE, 6, "Markdown,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.bash", CODE_SOURCE, 7, "Bash,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.zsh", CODE_SOURCE, 8, "Zsh,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.mermaid", CODE_SOURCE, 9, "Mermaid,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.drawio", CODE_SOURCE, 10, "Drawio,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.plantuml", CODE_SOURCE, 11, "Plantuml,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.json", CODE_SOURCE, 12, "Json,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.yaml", CODE_SOURCE, 13, "Yaml,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.toml", CODE_SOURCE, 14, "Toml,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.rust", CODE_SOURCE, 15, "Rust,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.typescript", CODE_SOURCE, 16, "Typescript,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.javascript", CODE_SOURCE, 17, "Javascript,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.python", CODE_SOURCE, 18, "Python,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.html", CODE_SOURCE, 19, "Html,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.css", CODE_SOURCE, 20, "Css,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf(CODE, "code.sql", CODE_SOURCE, 21, "Sql,", "public_show_code_block_menu_maps_all_kinds_and_lifecycle"),
    leaf_with_host(IMAGE, "image.file", IMAGE_SOURCE, 13, "AppAction::IngestImageFile", "public_show_image_ingest_routes_file_clipboard_and_file_url", EXTERNAL_INGEST_HOST_E2E),
    leaf_with_host(IMAGE, "image.clipboard-image", IMAGE_SOURCE, 20, "AppAction::IngestClipboardImage", "public_show_image_ingest_routes_file_clipboard_and_file_url", EXTERNAL_INGEST_HOST_E2E),
    leaf_with_host(IMAGE, "image.clipboard-file-url", "crates/katana-ui/src/views/panels/editor/text_edit.rs", 177, "AppAction::IngestClipboardImage", "public_show_image_ingest_routes_file_clipboard_and_file_url", MISSING_HOST_E2E),
];
